Repository 2223-Project-1/OmegaPass, pull requests merged in 2023-05, with the labels that each got.

#40 feat: rewrite get pass for details bar
  ajax/ajax.php
  composer.json
  composer.lock
  css/overview.css
  db.php
  js/overview.js
  overview/index.php
  tests/DbTest.php
Labels: feature

#44 feat: Add favicon and welcome
  Omegapass.gif
  account-settings/index.php
  add-password/index.php
  css/index.css
  index.php
  js/index.js
  omegapass.jpg
  overview/index.php
Labels: feature

#46 Chore: composer in fpm container
  Dockerfile
  docker-compose.yaml
Labels: feature

#51 refactor: Move pages to public folder
  default.conf
  public/Omegapass.gif
  public/account-settings/index.php
  public/add-password/index.php
  public/ajax/ajax.php
  public/css/account-settings.css
  public/css/add-password.css
  public/css/index.css
  public/css/overview.css
  public/index.php
  public/js/account-settings.js
  public/js/add-password.js
  public/js/index.js
  public/js/overview.js
  public/omegapass.jpg
  public/overview/index.php
Labels: refactor

#54 feat/#50
  public/css/index.css
  public/css/overview.css
  public/index.php
  public/js/index.js
  public/js/overview.js
  public/overview/index.php
Labels: feature

#45 feat: save userId in session
  db.php
  public/account-settings/index.php
  public/add-password/index.php
  public/overview/index.php
  tests/DbTest.php
Labels: feature

#56 fix: session security
  config.php
  public/account-settings/index.php
  public/add-password/index.php
  public/ajax/ajax.php
  public/index.php
  public/overview/index.php
Labels: security

#58 Feat/regulation#32
  public/css/imprint.css
  public/css/index.css
  public/css/overview.css
  public/css/privacy-policy.css
  public/imprint/index.php
  public/index.php
  public/overview/index.php
  public/privacy-policy/index.php
Labels: feature

#53 feat: upscale omegapass icon
  public/omegapass.jpg
Labels: feature

#55 feat: Style
  README.md
  public/account-settings/index.php
  public/add-password/index.php
  public/css/_colors.scss
  public/css/_mixins.scss
  public/css/account-settings.css
  public/css/account-settings.scss
  public/css/add-password.css
  public/css/add-password.scss
  public/css/imprint.css
  public/css/imprint.scss
  public/css/index.css
  public/css/index.scss
  public/css/overview.css
  public/css/overview.scss
  public/css/privacy-policy.css
  public/css/privacy-policy.scss
  public/js/overview.js
  public/overview/index.php
Labels: feature

#63 feat: issue yml builder
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: feature, refactor

#64 pref: uglify js files
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.php
  public/js/index.min.js
  public/js/overview.min.js
  public/overview/index.php
Labels: refactor, security

#62 feat: add dialogs as modals
  .gitignore
  CONTRIBUTING.md
  README.md
  config.php
  crypt.php
  db.php
  package-lock.json
  package.json
  public/account-settings/index.php
  public/add-password/index.php
  public/ajax/account-settings.php
  public/ajax/add-password.php
  public/ajax/ajax.php
  public/ajax/edit-password.php
  public/css/_account-settings.scss
  public/css/_add-password.scss
  public/css/_colors.scss
  public/css/_edit-modal.scss
  public/css/_mixins.scss
  public/css/account-settings.css
  public/css/account-settings.scss
  public/css/add-password.css
  public/css/add-password.scss
  public/css/imprint.css
  public/css/imprint.scss
  public/css/index.css
  public/css/index.scss
  public/css/overview.css
  public/css/overview.scss
  public/css/privacy-policy.css
  public/css/privacy-policy.scss
  public/imprint/index.php
  public/index.php
  public/js/account-settings.js
  public/js/add-password.js
  public/js/index.min.js
  public/js/overview.js
  public/js/overview.min.js
  public/overview/index.php
  public/privacy-policy/index.php
  tests/DbTest.php
Labels: feature, refactor

#66 fix: #65 - change where statments for gathering passwords
  db.php
  public/css/overview.css
  public/css/overview.scss
Labels: bug

#68 chore: add favicon file
  public/favicon.ico
  public/imprint/index.php
  public/index.php
  public/overview/index.php
  public/privacy-policy/index.php
Labels: refactor
