Repository 2223-Project-1/OmegaPass, pull requests merged in 2023-04, with the labels that each got.

#26 docs: improve project docs
  account-settings/index.php
  add-password/index.php
  ajax/ajax.php
  crypt.php
  db.php
  index.php
  js/account-settings.js
  js/add-password.js
  js/overview.js
  overview/index.php
Labels: documentation

#25 test: unit tests and CICD GitHub Action pipeline for testing
  .github/workflows/phpunit.yml
  Dockerfile
  composer.json
  composer.lock
  crypt.php
  db.php
  docker-compose.yaml
  phpunit.xml
  tests/CryptTest.php
  tests/DbTest.php
Labels: feature

#28 feat: add github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, feature

#36 bug: check if user has auth if not redirect to homepage
  .github/workflows/phpunit.yml
  account-settings/index.php
  add-password/index.php
  ajax/ajax.php
  overview/index.php
Labels: bug

#38 docs: add contributing manifest
  CONTRIBUTING.md
Labels: documentation, feature
